services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    user: root
    restart: always
    command:  uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=postgresql+asyncpg://abduvohid:20042629ab@db:5432/my_database
    volumes:
      - ./app/static:/media_service/static
      - ./app/media:/media_service/media

  db:
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: abduvohid
      POSTGRES_PASSWORD: 20042629ab
      POSTGRES_DB: my_database
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_
    ports:
      - "6370:6379"


volumes:
  db_data:
  static_volume: 
  media_volume:   
